V3
UW-Macrostrat/macrostrat-api pull request #225
Opened 2024-04-18 15:01 UTC by aran-swamy

Includes changes made to allow test discoverability with `yarn run test`, commented notes for ES6 updates, and examples to fix initial errors for the unit tests.

2024-04-18 17:15 UTC, davenquinn requested changes
This looks pretty good. A few small questions and suggested fixes. If you don't have time to implement these, I can go ahead and merge into another branch and pull in eventually.

2024-04-18 17:15 UTC, davenquinn commented on package.json
> +    "test": "mocha --require ts-node/register/transpile-only './v2test/test/test.js'",
Can you add a npm script that both transpiles with `tsc` and runs `mocha` so the whole testing process can run in one shot?

2024-04-18 17:15 UTC, davenquinn commented on server.js
Is there a reason that this file is added back in? Seems like it is used for the tests only...if so could it be moved to a specific "tests" directory?

2024-04-18 17:15 UTC, davenquinn commented on server.ts
If this is kept, it will make the app not run in "normal" mode, right? Or maybe we just need to make sure we run `tsc` before starting the server?

2024-04-20 18:21 UTC, aran-swamy commented on server.js
I have made modifications to the test.ts file to no longer need this file, server.ts is sufficient.

2024-04-22 07:01 UTC, merged